all: server.c client.c
	gcc server.c -o server
	gcc client.c -o client
	./server 
100: 
	gcc server.c -o server
	gcc client.c -o client
	./server 100

mb: 
	gcc server.c -o server
	gcc client.c -o client
	./server 1000000